BEGIN TRANSACTION;

CREATE TABLE `Station` (
	`StationsID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Stationsname`	TEXT NOT NULL
);
CREATE TABLE `Ort` (
	`OrtsID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Ortsname`	TEXT NOT NULL
);
CREATE TABLE `Kunde` (
	`KundenNr`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`EMail`	TEXT NOT NULL,
	`Nachname`	TEXT NOT NULL,
	`Vorname`	TEXT NOT NULL,
	`TelNr`	TEXT NOT NULL,
	`PSW`	TEXT NOT NULL
);
CREATE TABLE "Fahrzeug" (
	`FahrzeugID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Beschreibung`	TEXT NOT NULL,
	`Hersteller`	TEXT NOT NULL,
	`Modell`	TEXT NOT NULL,
	`Preis/Tag`	TEXT NOT NULL,
	`Bild`	TEXT NOT NULL
);
CREATE TABLE "Buchung" (
	`BuchungsID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Kunde`	INTEGER NOT NULL,
	`Fahrzeug`	INTEGER NOT NULL,
	`Abholstation`	INTEGER NOT NULL,
	`RückgabeStation`	INTEGER NOT NULL,
	`Abholdatum`	TEXT NOT NULL,
	`Abholzeit`	TEXT NOT NULL,
	`Rückgabedatum`	TEXT NOT NULL,
	`Rückgabezeit`	TEXT NOT NULL,
	FOREIGN KEY(Fahrzeug) REFERENCES Fahrzeug(FahrzeugID),
	FOREIGN KEY(Kunde) REFERENCES Kunde(KundenNr)
);
CREATE TABLE `Ausstattung` (
	`AusstattungsID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Ausstattungsname`	TEXT NOT NULL,
	`Beschreibung`	TEXT NOT NULL
);
CREATE TABLE "Adresse" (
	`AdressID`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`Strasse`	TEXT NOT NULL,
	`HausNr`	TEXT NOT NULL,
	`PLZ`	TEXT NOT NULL
);
;
;
;
;
;
;
;
COMMIT;
